version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=orders_user
      - POSTGRES_PASSWORD=Orders@Admin
      - POSTGRES_DB=orderdb
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=hyderabadczar@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 80:80